#![allow(dead_code)]
use crate::app::Message;

#[derive(Debug, Clone)]
pub enum Action {
    Quit,
    ConfirmQuit,
    CancelModal,
    SendMessage(String),
    StreamResponse(usize, usize, String),
    StreamThinking(usize, usize, String),
    #[cfg(feature = "memory")]
    SetMemoryActivities(usize, usize, Vec<crate::memory::MemoryActivity>),
    FinalizeAssistantMessage(usize, usize, Message),
    StopStream(usize),
    AddMessage(usize, Message),
    AddGeneratedFile(usize, crate::app::GeneratedFile),
    LoadConversation(i64),
    NewConversation(usize),
    UpdateModel(String),
    UpdateStatus(String),
    ShowToast(String),
    SetConnectionState(crate::ui::status_bar::ConnectionStatus, Option<String>),
    SetTitle(String),
    SwitchTab(usize),
    AddTab(crate::app::Tab),
    RemoveTab(usize),
    NewChat,
    CloseChat,
    ToggleSidebar,
    ToggleArtifactSidebar,
    ToggleSessionList,
    FocusInput,
    ClearConversation,
    ExportConversation,
    ExportConversationId(i64),
    ToggleConversationPinned(i64),
    DeleteConversation(i64),
    RenameConversation(String),
    ScrollUp,
    ScrollDown,
    ShowQuitConfirm,
    ShowHelp,
    DismissHelp,
    ShowKeybinds,
    DismissKeybinds,
    ShowSettings,
    CloseSettings,
    ToggleSettings,
    UpdateTabProvider(usize, String),
    UpdateTabModel(usize, String),
    SetProviderModels(String, Vec<crate::ui::ModelInfo>),
    SaveApiKey(String, String),
    MouseClick(MouseClickAction),
    SaveGeneratedFile,
    SaveExportDialog,
    CancelSaveDialog,
    RefreshModels,
    ToggleWebSearch,
    ShowSkillsPopup,
    ShowMcpPopup,
    ShowLocalSearch(String),
    CloseListPopup,
    RefreshArtifactSidebar,
    OpenCommandPalette,
    OpenSettingsPanel,
    SetPinnedCommands(Vec<String>),
    ToggleCollapseThinking,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MouseClickAction {
    SelectPaletteItem(usize),
    ToggleLeftHandle,
    ToggleRightHandle,
    CloseRightSidebar,
    SetRightSidebarThin,
    OpenProviderDropdown,
    OpenModelDropdown,
    SelectSettingsItem(usize),
}
